---
- name: "Updating Debian apt"
  apt:
    update_cache: yes
    allow_unauthenticated: yes
  ignore_errors: yes

- name: "Installing required Debian packages for version equal or greather than 9"
  apt:
    name: "{{item}}"
  vars:
    force: yes
    force_apt_get: yes
    item:
    - make
    - g++
    - libpcre2-dev
    - libevent-dev
    - libz-dev
    - libssl-dev
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 9)

- name: "Installing required Debian packages on versions older than 9"
  apt:
    name: "{{item}}"
  vars:
    force: yes
    force_apt_get: yes
    item:
    - make
    - g++
  when: ( ansible_distribution == "Debian" and ansible_distribution_major_version|int < 9)
